name: flutter_soloud
description: Flutter audio plugin using SoLoud library and FFI
version: 0.9.0
homepage: https://github.com/alnitak/flutter_soloud
maintainer: Marco Bavagnoli (@lildeimos)

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  
  #https://pub.dev/packages/ffi
  ffi: ^2.0.2

  plugin_platform_interface: ^2.1.5

dev_dependencies:
  #https://pub.dev/packages/ffigen
  ffigen: ^9.0.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true


